Provide dataset parser handler
qbicsoftware/java-openbis-dropboxes pull request #1
Opened 2021-05-10 08:03 UTC by sven1103

This PR introduces a parser handler class, that will brute force data set parsing based on given implementations
of `DataSetParser`.

2021-05-10 08:31 UTC, KochTobi requested changes
Hi Sven, the code looks good. However, one test seems to be written incorrectly (it never fails). Furthermore, I would suggest adding a test that unexpected exceptions are indeed thrown and not silently caught (RuntimeExceptions). In case it is the desired behaviour that the first successful dataset parsing shall exit the execution and return the values it would also make sense to add a small test that provides two valid parsers. What do you think?

2021-05-10 08:31 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +    }
This test does not seem to work. When I replace the DataParserException with a type of exception I do not expect here the test does not fail.

2021-05-10 08:31 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +        ParserHandler handler = new ParserHandler([failingParser])
```suggestion
        ParserHandler handler = new ParserHandler([failingParser])
        handler.parseFrom(<somewhere>)
```
there is no call here

2021-05-10 08:31 UTC, KochTobi commented on src/main/groovy/life.qbic.registration/ParserHandler.groovy
> +     */
Add javadoc formatting, simplification of text for `return` annotation
```suggestion
    /**
     * <p>Tries to parse a given file structure into a dataset.<p>
     *
     * <p>The return type is not known during compile time, because
     * this method brute forces a file structure with different
     * available parsers, to determine the dataset type.</p>
     *
     * <p>The return <code>Optional</code> object is empty, if no registered parser was able to
     * determine the dataset successfully. The dataset type is determined during runtime.</p>
     *
     * <p>In case the return <code>Optional</code> contains a value, you need to determine the type
     * by Java's explicit type conversion in order to make use of static typing in any
     * downstream code that consumes dataset objects.</p>
     *
     * @param root the top level path of the directory with the file structure to be parsed.
     * @return the parsed dataset. Optional.empty(), if no parser was able to parse the file structure to a dataset.
     * @since 1.0.0
     */
```

2021-05-10 08:32 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +    }
```
    Optional<?> parseFrom(Path root) {
        /*Iterator<DataSetParser> dataSetIterator = dataSetParserList.iterator()
        Optional<?> result = Optional.empty()
        while (dataSetIterator.hasNext()) {
            try {
                DataSetParser parser = dataSetIterator.next()
                result = Optional.of(parser.parseFrom(root))
            } catch (DataParserException e) {
                // log it maybe
            } catch (DataSetValidationException e){
                // log it maybe
            }
            if (result.isPresent())
                return result
        }
        return result*/
        throw new RuntimeException("Test is incorrect")
    }
```
and the test succeeds.

2021-05-10 08:41 UTC, KochTobi reviewed
Suggestions to prevent others from the same mistake I did when reading the tests

2021-05-10 08:41 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +        given:
```suggestion
        given: "an implementation of the DatasetParser interface"
```

2021-05-10 08:41 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +        when:
```suggestion
        when: "an instance of the ParserHandler is created"
```

2021-05-10 08:41 UTC, KochTobi commented on src/test/groovy/ParserHandlerSpec.groovy
> +        then:
```suggestion
        then: "no exceptions are thrown"
```

2021-05-10 08:50 UTC, KochTobi commented on src/main/groovy/life.qbic.registration/ParserHandler.groovy
> +        Iterator dataSetIterator = dataSetParserList.iterator()
```suggestion
        Iterator<DataSetParser> dataSetIterator = dataSetParserList.iterator()
```
Nit :)

2021-05-10 08:50 UTC, KochTobi commented on src/main/groovy/life.qbic.registration/ParserHandler.groovy
> +                def parser = dataSetIterator.next()
```suggestion
                DataSetParser parser = dataSetIterator.next()
```
Nit

2021-05-10 08:50 UTC, KochTobi commented on src/main/groovy/life.qbic.registration/ParserHandler.groovy
> +                // log it maybe
```suggestion
                // log it !
```

2021-05-10 08:50 UTC, KochTobi commented on src/main/groovy/life.qbic.registration/ParserHandler.groovy
> +                // log it maybe
```suggestion
                // log it !
```
I think we should log at least that there was an unsuccessful attempt. Otherwise, we wonder later on what happened. Does not have to be a lot of detail.

2021-05-10 10:01 UTC, KochTobi commented
I really like the documentation 👍  (of the code as well as of the tests)

2021-05-10 10:49 UTC, merged

2021-06-09 06:36 UTC, sven1103 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finalise Java ETL for nf-core pipeline result registration](https://trello.com/c/iUV2yvjG/776-finalise-java-etl-for-nf-core-pipeline-result-registration)