Provide MaxQuant registry
qbicsoftware/java-openbis-dropboxes pull request #12
Opened 2021-07-12 13:16 UTC by sven1103

This PR adds a registry for MaxQuant analysis results. Addresses #9 .

2021-07-14 13:50 UTC, sven1103 commented
![](https://github.trello.services/images/mini-trello-icon.png) [MaxQuant: Write ETL max quant registry class in java openBiS dropbox](https://trello.com/c/U4anpPWL/854-maxquant-write-etl-max-quant-registry-class-in-java-openbis-dropbox)

2021-07-15 07:57 UTC, KochTobi requested changes
Hi @sven1103 
You code looks good for the most part. I have a few suggestions regarding the code structure and minor changes. Also, I looked over the `MaxQuantResultRegistry` and the code looks good there. However, since I am not proficient in the openBis API I wonder if it would be possible to provide some tests to prove functionality?

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +        return sampleIds ? Optional.of(sampleIds) : Optional.empty() as Optional<List<String>>
```
Cannot return 'Optional<? extends List>' from method returning 'Optional<List<String>>'
```
The `def` keyword creates a class `? extends List` which is not necessarily a `List<String>`. I would suggest casting it here or replacing the `def` with the `List<String>` interface.

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> + * @since 1.1.0
Do we really want to introduce a Utils class? I would say it is more declarative to have static classes with single responsibilities (e.g. SampleParser and ContextProvider)

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +     * @return
Please provide JavaDoc for the `@since 1.1.0` tag and the return value of the method.

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +        SearchCriteria sc = new SearchCriteria()
Please be more declarative.
```suggestion
        SearchCriteria searchCriteria = new SearchCriteria()
```

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +     * @throws RuntimeException if at least one sample id cannot be converted
This public method is missing its `@since` JavaDoc

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +    static List<SampleId> validateSampleIds(List<String> sampleIdList) throws RuntimeException {
Where does the validation happen? Is it done in the `SampleId.from` call? Since this method technically converts strings to objects and returns them I wonder whether we should change the method name to `getValidSampleIds`

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> +    static List<SampleId> validateSampleIds(List<String> sampleIdList) throws RuntimeException {
Otherwise very concise and clear implementation :+1:

2021-07-15 07:57 UTC, KochTobi commented on CHANGELOG.rst
> +-----
The date is missing.
```suggestion
1.1.0 (2021-07-15)
------------------
```

2021-07-15 07:57 UTC, KochTobi commented on CHANGELOG.rst
> +* MaxQuantResultRegistry for MaxQuant analysis result datasets
```suggestion
* Add MaxQuantResultRegistry for MaxQuant analysis result datasets (`#12 <https://github.com/qbicsoftware/java-openbis-dropboxes/pull/12>`_)
```

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/MaxQuantResultRegistry.groovy
> +            } catch (NumberFormatException e) {
```suggestion
            } catch (NumberFormatException ignored) {
```
I suggest renaming it to ignored to indicate it is not used in the catch block

2021-07-15 07:57 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/MaxQuantResultRegistry.groovy
> +        for (SampleId sampleId : sampleIdList) {
we could use 
```suggestion
        sampleIdList.each { SampleId sampleId ->
```

2021-07-15 08:01 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> + * @since 1.1.0
Until now, i just wanted to create a collection of static utility methods, and combine them in one class to also indicate that they should be reused. Of course there is more than one way to do it.

2021-07-15 08:05 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/MaxQuantResultRegistry.groovy
> +        for (SampleId sampleId : sampleIdList) {
This is only NIT

2021-07-15 08:07 UTC, sven1103 commented on CHANGELOG.rst
> +-----
There is not release that yet. I consider this to be filled when the actual release is prepared

2021-07-15 08:10 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/registries/MaxQuantResultRegistry.groovy
> +        for (SampleId sampleId : sampleIdList) {
ah, thats NIT ;) I consider this personal preference of language usage. Also, the classical `for` approach is always the more performant compare to closures. Though performance is not the key feature here.

2021-07-15 08:23 UTC, KochTobi requested changes
Thank you for addressing my requests. However, I would really like to avoid having `util` classes around.

2021-07-15 08:23 UTC, KochTobi commented on CHANGELOG.rst
> +-----
I am not sure whether it will pass the qube tests then.

2021-07-15 08:23 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/MaxQuantResultRegistry.groovy
> +        for (SampleId sampleId : sampleIdList) {
Yes, I also prefer the for loop. I simply wanted to point out the possibility.

2021-07-15 08:23 UTC, KochTobi commented on src/main/groovy/life/qbic/registration/registries/Utils.groovy
> + * @since 1.1.0
I personally would prefer the approach of separating them into static classes. If I had wanted to validate a sample id, for example, I would have written the functionality myself since it would not have been obvious to me that the functionality already exists. In contrast to this if I would have seen an appropriate package (screaming architecture) I could have found it more easily.

2021-07-15 08:43 UTC, KochTobi approved these changes
Perfect 👍 LGTM

2021-07-15 08:50 UTC, merged