Finalise nfcore registry
qbicsoftware/java-openbis-dropboxes pull request #3
Opened 2021-06-18 09:00 UTC by sven1103

2021-06-21 06:56 UTC, sven1103 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Java ETL: Finish the implementation for the registration of an nf-core result dataset in the NfCoreResultRegistry.](https://trello.com/c/jWPiFJV4/796-java-etl-finish-the-implementation-for-the-registration-of-an-nf-core-result-dataset-in-the-nfcoreresultregistry)

2021-06-21 14:12 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/DatasetParserHandler.groovy
> +                observedExceptions << e
they are never thrown or requested from other class?

2021-06-21 14:14 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/DatasetParserHandler.groovy
> +                observedExceptions << e
ah, the getter is implicit?

2021-06-21 14:42 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
>              parentSamples.add(sample)
why collect all parent samples when you have the ids anyhow?
the check if they exist might be useful though

2021-06-21 14:44 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
> +        PIPELINE_TO_ANALYSIS.put("nf-core/sarek", AnalysisType.VARIANT_CALLING)
this does not seem to be used, I assume it should be set as a property?

2021-06-21 14:46 UTC, wow-such-code requested changes
nice solution!
i have a few questions, though

2021-06-23 06:10 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/DatasetParserHandler.groovy
> +                observedExceptions << e
yes, this is just a collection of all parser exceptions, in case one wants to access them for debugging purposes

2021-06-23 06:12 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
>              parentSamples.add(sample)
because we want to set them as parent samples to the result sample. For that i need Objects implementing the ISample interface, not our own class.
but maybe we can add an assertion, that both lists have the same length.

2021-06-23 06:12 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
> +        PIPELINE_TO_ANALYSIS.put("nf-core/sarek", AnalysisType.VARIANT_CALLING)
refactored now

2021-06-23 07:58 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
>              parentSamples.add(sample)
To my knowledge you set parents via identifiers, no? It's still a NIT, so I don't mind

2021-06-23 08:02 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/handler/registries/NfCoreResultRegistry.groovy
> +        println "${sampleIdList[0].getProjectCode().toString()}R"
```suggestion
        log.info "${sampleIdList[0].getProjectCode().toString()}R"
```

2021-06-23 10:22 UTC, wow-such-code approved these changes
hit the button!

2021-06-24 06:11 UTC, merged