remove hidden files in the file structure before registration
qbicsoftware/java-openbis-dropboxes pull request #36
Opened 2022-06-21 13:44 UTC by wow-such-code

Removes all hidden files in the file structure of a dataset, as they are often added when browsing the data in different OS utilities.

2022-06-21 14:25 UTC, sven1103 requested changes
Dear @wow-such-code thanks for your contribution.

Since the removal of files during registration is a very critical task, I would like to see 
some unit tests here.

2022-06-22 08:54 UTC, sven1103 reviewed
A suggestion for the interface

2022-06-22 08:54 UTC, sven1103 commented on src/main/groovy/life/qbic/registration/handler/DatasetCleaner.groovy
> +    void removeUnwantedFiles(Path root)
Now that I read over it more closely, I am a little irritated by the abstraction. I think a interface of a dataset cleaner should just have one method: `clean(Path datasetRoot)`.

And then you can have multiple implementations, such as your `HiddenFileDataSetCleaner`. I think this will be way more expressive, than `unwanted files`. What are unwanted files?

2022-06-22 08:54 UTC, sven1103 commented on src/test/groovy/life/qbic/registration/handler/HiddenFilesCleanerSpec.groovy
> +        visibleFiles.add(File.createTempFile("tables", ".pdf", level2))
I love the test. Just one NIT comment: is the complexity of the file composition necessary for the unit test? Makes it harder to read and understand

2022-06-22 08:56 UTC, wow-such-code commented on src/test/groovy/life/qbic/registration/handler/HiddenFilesCleanerSpec.groovy
> +        visibleFiles.add(File.createTempFile("tables", ".pdf", level2))
I thought I would test it with a (large) subset of the Maxquant input

2022-06-22 08:58 UTC, wow-such-code commented on src/main/groovy/life/qbic/registration/handler/DatasetCleaner.groovy
> +    void removeUnwantedFiles(Path root)
agreed, and fixed

2022-06-22 09:11 UTC, merged